name: nigeria_geo_sdk
description: High-performance Flutter SDK for comprehensive Nigerian geographic data including states, LGAs, wards, and postal codes. Zero configuration required.
version: 1.1.1
homepage: https://github.com/mubarakhammed/3609ja/tree/main/mobile-sdks/flutter
repository: https://github.com/mubarakhammed/3609ja
documentation: https://github.com/mubarakhammed/3609ja/blob/main/mobile-sdks/flutter/README.md
issue_tracker: https://github.com/mubarakhammed/3609ja/issues
funding:
  - https://github.com/sponsors/mubarakhammed
topics:
  - nigeria
  - geography
  - location
  - maps
  - api

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependencies sorted alphabetically
  geolocator: ^9.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  json_annotation: ^4.8.0
  logger: ^1.3.0
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  rxdart: ^0.27.7
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Dependencies sorted alphabetically
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  json_serializable: ^6.6.2
  mockito: ^5.4.0

flutter:
  # SDK uses built-in configuration - no assets needed
# Uncomment if dependency overrides are needed
# dependency_overrides:
