[server]
host = "127.0.0.1"
port = 3000
workers = 4

[database]
url = "postgresql://localhost/rust_backend"
max_connections = 10
min_connections = 1
acquire_timeout = 30
idle_timeout = 600

[jwt]
secret = "your-super-secret-jwt-key-change-this-in-production"
expiration = 3600
issuer = "rust-backend"

[cors]
allowed_origins = ["http://localhost:3000", "http://localhost:3001"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["*"]
